require 'rake/testtask'
require 'rake/extensiontask'
require 'rubygems/package_task'

spec = Gem::Specification.new do |s|
  s.name        = 'stash'
  s.version     = '2.0.0'
  s.date        = '2012-06-24'
  s.summary     = "High perfomance mustache rendering engine written in C with extensions for Ruby"
  s.description = "High perfomance mustache rendering engine written in C with extensions for Ruby"
  s.authors     = ['J.P. Cummins']
  s.email       = 'jpcummins@gmail.com'
  s.files       = Dir.glob('lib/**/*.rb') +
                  Dir.glob('ext/**/*.{c,h,rb}')
  s.extensions  = ['ext/stash/extconf.rb']
  s.homepage    = 'https://github.com/jpcummins/stash'
end

Gem::PackageTask.new(spec) do |pkg|
end

Rake::ExtensionTask.new do |ext|
  ext.name = 'stash'
  ext.lib_dir = 'lib/stash'
  ext.ext_dir = 'ext/stash'
  ext.gem_spec = spec
end

Rake::TestTask.new do |t|
  t.libs << 'test'
end

desc "Run tests"
task :default => :test
